server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZOne: http://${eureka.instance.hostname}/8761/eureka

spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school-student-microservice
    username: postgres
    password: 206207
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true